name = input("enter your name : ")
print("hello" , name )
age = input("enter your age : ")
print(name + "'s age is " + age + " yrs old")
nickname = input("enter your nickname : ")
print("your nick name is " , nickname)
food = input("enter your favourite food : ")
print(name + "'s favourite foods are " + food)
color = input("enter your favourite color : ")
print(name + "'s favourite color is " + color)
study = input("enter your study field : ")
print(name + "'s study field is " + study)
marks = input("enter your marks : ")
print(name + "'s percentage is " + marks + "%")
